// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/about.tsx";
import * as $1 from "./routes/api/[id].ts";
import * as $2 from "./routes/api/github.ts";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/using_island/github.ts";
import * as $5 from "./routes/using_island/github.tsx";
import * as $6 from "./routes/using_island_with_queries/github.tsx";
import * as $7 from "./routes/using_no_island/github.ts";
import * as $8 from "./routes/using_no_island/github.tsx";
import * as $$0 from "./islands/SearchGithubUser.tsx";
import * as $$1 from "./islands/SearchGithubUserWithQueries.tsx";

const manifest = {
  routes: {
    "./routes/about.tsx": $0,
    "./routes/api/[id].ts": $1,
    "./routes/api/github.ts": $2,
    "./routes/index.tsx": $3,
    "./routes/using_island/github.ts": $4,
    "./routes/using_island/github.tsx": $5,
    "./routes/using_island_with_queries/github.tsx": $6,
    "./routes/using_no_island/github.ts": $7,
    "./routes/using_no_island/github.tsx": $8,
  },
  islands: {
    "./islands/SearchGithubUser.tsx": $$0,
    "./islands/SearchGithubUserWithQueries.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
